# Generated by Django 3.0.5 on 2020-07-21 15:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test1',
            name='file',
            field=models.FileField(default=datetime.datetime(2020, 7, 21, 15, 53, 41, 511100, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
    ]
