# Generated by Django 3.0.1 on 2021-01-10 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test44',
        ),
        migrations.DeleteModel(
            name='test44Accepted',
        ),
    ]
