# Generated by Django 3.0.7 on 2020-08-14 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test987',
        ),
        migrations.DeleteModel(
            name='test987Accepted',
        ),
        migrations.DeleteModel(
            name='testtt',
        ),
        migrations.DeleteModel(
            name='testttAccepted',
        ),
    ]
