# Generated by Django 3.0.1 on 2020-12-28 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test1',
        ),
        migrations.DeleteModel(
            name='test1Accepted',
        ),
    ]
