# Generated by Django 3.0.7 on 2020-08-08 13:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='test1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_is_your_name', models.CharField(max_length=1000)),
                ('sasa', models.CharField(max_length=1000)),
                ('date_choose', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='test1Accepted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('what_is_your_name', models.CharField(max_length=1000)),
                ('sasa', models.CharField(max_length=1000)),
                ('date_choose', models.DateField()),
            ],
        ),
    ]
