# Generated by Django 3.0.5 on 2020-12-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_test11_test11accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formindex',
            name='commentByAuthor',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='formindex',
            name='responseAcceptedStatus',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
