# Generated by Django 3.0.5 on 2020-07-21 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_test1_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test1',
        ),
        migrations.DeleteModel(
            name='test1Accepted',
        ),
    ]
