# Generated by Django 3.0.5 on 2020-08-09 13:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20200809_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='test1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dfaf', models.CharField(max_length=1000)),
                ('fafds', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='test1Accepted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('dfaf', models.CharField(max_length=1000)),
                ('fafds', models.CharField(max_length=1000)),
            ],
        ),
    ]
