# Generated by Django 3.0.5 on 2020-05-04 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_forms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Forms',
        ),
    ]
