# Generated by Django 3.0.1 on 2020-12-28 15:50

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20201228_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='test2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responseID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('responseTime', models.DateTimeField(auto_now_add=True)),
                ('responseStatus', models.BooleanField(default=False)),
                ('userName', models.CharField(blank=True, max_length=1000)),
                ('userMail', models.EmailField(max_length=1000)),
                ('userDept', models.CharField(max_length=1000)),
                ('dasfdsa', models.CharField(max_length=1000)),
                ('gsdfgdf', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='test2Accepted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptedResponseID', models.CharField(max_length=1000)),
                ('responseTime', models.DateTimeField(auto_now_add=True)),
                ('comment', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('forwardTo', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(null=True), blank=True, default=list, size=None)),
                ('commentByAuthor', models.CharField(blank=True, max_length=10000)),
                ('notification', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('userName', models.CharField(blank=True, max_length=1000)),
                ('committedamount', models.PositiveIntegerField(blank=True, default=0)),
                ('recommendedamount', models.PositiveIntegerField(blank=True, default=0)),
                ('pipelinedamount', models.PositiveIntegerField(blank=True, default=0)),
                ('expenditureamount', models.PositiveIntegerField(blank=True, default=0)),
                ('userDept', models.CharField(max_length=1000)),
                ('dasfdsa', models.CharField(max_length=1000)),
                ('gsdfgdf', models.CharField(max_length=1000)),
            ],
        ),
    ]
