# Generated by Django 3.0.7 on 2020-08-14 20:34

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_test1_test1accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentform1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.CharField(max_length=1000)),
                ('sasa', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='paymentform1Accepted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('forwardTo', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('fields', models.CharField(max_length=1000)),
                ('sasa', models.CharField(max_length=1000)),
            ],
        ),
    ]
