# Generated by Django 3.0.5 on 2020-08-02 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_test1_test1accepted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test1',
        ),
        migrations.DeleteModel(
            name='test1Accepted',
        ),
    ]
