# Generated by Django 3.0.7 on 2020-12-09 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_tetest1_tetest1accepted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tetest1',
        ),
        migrations.DeleteModel(
            name='tetest1Accepted',
        ),
    ]
