# Generated by Django 3.0.7 on 2021-01-10 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_test33_test33accepted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test33',
        ),
        migrations.DeleteModel(
            name='test33Accepted',
        ),
    ]
