# Generated by Django 3.0.5 on 2020-12-02 13:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_test1_test1accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='formname',
            name='department',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
