# Generated by Django 3.0.7 on 2020-12-02 19:42

import datetime
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_test102'),
    ]

    operations = [
        migrations.CreateModel(
            name='test102Accepted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responseTime', models.DateTimeField(auto_now_add=True)),
                ('comment', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('forwardTo', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(null=True), blank=True, default=list, size=None)),
                ('commentAccepted', models.CharField(blank=True, max_length=1000)),
                ('notification', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('userName', models.CharField(blank=True, max_length=1000)),
                ('sasasadasdasdasdas', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='test102',
            name='sasasadasdasdasdas',
            field=models.CharField(default=datetime.datetime(2020, 12, 2, 19, 42, 12, 537229, tzinfo=utc), max_length=1000),
            preserve_default=False,
        ),
    ]
