# Generated by Django 3.0.5 on 2020-08-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_hello1_hello1accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='sadsa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sd', models.CharField(max_length=1000)),
                ('sad', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='sadsaAccepted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=1000)),
                ('sd', models.CharField(max_length=1000)),
                ('sad', models.CharField(max_length=1000)),
            ],
        ),
    ]
