# Generated by Django 3.0.1 on 2020-12-28 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_test2_test2accepted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departmentdetail',
            old_name='availableamount',
            new_name='availableAmount',
        ),
        migrations.RenameField(
            model_name='departmentdetail',
            old_name='committedamount',
            new_name='committedAmount',
        ),
        migrations.RenameField(
            model_name='departmentdetail',
            old_name='deptname',
            new_name='deptName',
        ),
        migrations.RenameField(
            model_name='departmentdetail',
            old_name='expenditureamount',
            new_name='expenditureAmount',
        ),
        migrations.RenameField(
            model_name='departmentdetail',
            old_name='pipelinedamount',
            new_name='pipelinedAmount',
        ),
        migrations.RenameField(
            model_name='departmentdetail',
            old_name='recommendedamount',
            new_name='recommendedAmount',
        ),
    ]
