# Generated by Django 3.0.5 on 2020-10-30 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_test2_test2accepted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test2',
        ),
        migrations.DeleteModel(
            name='test2Accepted',
        ),
    ]
