# Generated by Django 3.0.5 on 2020-12-02 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_formname_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test1',
        ),
        migrations.DeleteModel(
            name='test1Accepted',
        ),
    ]
