# Generated by Django 3.0.5 on 2020-08-09 13:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_test1_test1accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='test3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asdasdasd', models.CharField(max_length=1000)),
                ('zxczvcx', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='test3Accepted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('asdasdasd', models.CharField(max_length=1000)),
                ('zxczvcx', models.CharField(max_length=1000)),
            ],
        ),
    ]
