# Generated by Django 3.0.5 on 2020-05-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_delete_forms'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
