# Generated by Django 3.0.5 on 2020-12-10 20:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20201211_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='formindex',
            name='formName',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
