# Generated by Django 3.0.1 on 2020-12-28 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20201229_0206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test2accepted',
            old_name='committedamount',
            new_name='committedAmount',
        ),
        migrations.RenameField(
            model_name='test2accepted',
            old_name='expenditureamount',
            new_name='expenditureAmount',
        ),
        migrations.RenameField(
            model_name='test2accepted',
            old_name='pipelinedamount',
            new_name='pipelinedAmount',
        ),
        migrations.RenameField(
            model_name='test2accepted',
            old_name='recommendedamount',
            new_name='recommendedAmount',
        ),
    ]
