# Generated by Django 3.0.5 on 2020-12-09 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_test11_test11accepted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test11',
        ),
        migrations.DeleteModel(
            name='test11Accepted',
        ),
    ]
