# Generated by Django 3.0.5 on 2020-07-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_test1_test1accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='teest2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdasdas', models.CharField(max_length=1000)),
                ('dadas', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='teest2Accepted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=1000)),
                ('sdasdas', models.CharField(max_length=1000)),
                ('dadas', models.CharField(max_length=1000)),
            ],
        ),
    ]
