# Generated by Django 3.0.5 on 2020-05-04 18:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_formname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formname',
            old_name='name',
            new_name='description',
        ),
        migrations.AddField(
            model_name='formname',
            name='title',
            field=models.CharField(default=datetime.datetime(2020, 5, 4, 18, 40, 0, 964812, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
