# Generated by Django 3.0.7 on 2020-08-18 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_test4_test4accepted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test12',
        ),
        migrations.DeleteModel(
            name='test12Accepted',
        ),
        migrations.DeleteModel(
            name='test3',
        ),
        migrations.DeleteModel(
            name='test3Accepted',
        ),
        migrations.DeleteModel(
            name='test4',
        ),
        migrations.DeleteModel(
            name='test4Accepted',
        ),
    ]
