# Generated by Django 3.0.7 on 2021-01-10 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_test1_test1accepted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test1',
        ),
        migrations.DeleteModel(
            name='test1Accepted',
        ),
    ]
