# Generated by Django 3.0.5 on 2020-08-17 15:55

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_test5_test5accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='test6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responseTime', models.DateTimeField(auto_now_add=True)),
                ('NAME', models.CharField(max_length=1000)),
                ('AGE', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='test6Accepted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responseTime', models.DateTimeField(auto_now_add=True)),
                ('comment', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('forwardTo', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(null=True), blank=True, default=list, size=None)),
                ('NAME', models.CharField(max_length=1000)),
                ('AGE', models.CharField(max_length=1000)),
            ],
        ),
    ]
