# Generated by Django 3.0.5 on 2020-05-04 20:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20200505_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='formname',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 5, 4, 20, 19, 8, 633643, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
