# Generated by Django 3.0.5 on 2020-10-31 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_test12_test12accepted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test12',
        ),
        migrations.DeleteModel(
            name='test12Accepted',
        ),
    ]
