# Generated by Django 3.0.7 on 2020-12-02 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_test1_test1accepted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test1',
        ),
        migrations.DeleteModel(
            name='test101',
        ),
        migrations.DeleteModel(
            name='test101Accepted',
        ),
        migrations.DeleteModel(
            name='test102',
        ),
        migrations.DeleteModel(
            name='test102Accepted',
        ),
        migrations.DeleteModel(
            name='test1Accepted',
        ),
    ]
