# Generated by Django 3.0.1 on 2020-12-30 08:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20201229_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotifications',
            name='acceptedResponseID',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
