# Generated by Django 3.0.7 on 2020-12-02 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_chahat2_chahat2accepted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chahat1',
        ),
        migrations.DeleteModel(
            name='chahat2',
        ),
        migrations.DeleteModel(
            name='chahat2Accepted',
        ),
        migrations.DeleteModel(
            name='testttt',
        ),
        migrations.DeleteModel(
            name='testtttAccepted',
        ),
        migrations.DeleteModel(
            name='testttttttttttttttt',
        ),
        migrations.DeleteModel(
            name='testtttttttttttttttAccepted',
        ),
    ]
