# Generated by Django 3.0.5 on 2020-05-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_formname_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formname',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
