# Generated by Django 3.0.5 on 2020-07-22 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_teest2_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='teest2',
        ),
        migrations.DeleteModel(
            name='teest2Accepted',
        ),
        migrations.DeleteModel(
            name='test1',
        ),
        migrations.DeleteModel(
            name='test1Accepted',
        ),
    ]
