# Generated by Django 3.0.5 on 2020-09-29 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_test1_test1accepted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test1',
        ),
        migrations.DeleteModel(
            name='test1Accepted',
        ),
    ]
