# Generated by Django 3.0.7 on 2021-01-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_chahat_chahataccepted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chahat',
            old_name='sasa',
            new_name='sasasa',
        ),
        migrations.RenameField(
            model_name='chahataccepted',
            old_name='sasa',
            new_name='sasasa',
        ),
        migrations.AlterField(
            model_name='chahat',
            name='naaam',
            field=models.CharField(choices=[('ram', 'ram'), ('sham', 'sham'), ('ravi', 'ravi'), ('ras', 'ras')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='chahataccepted',
            name='naaam',
            field=models.CharField(choices=[('ram', 'ram'), ('sham', 'sham'), ('ravi', 'ravi'), ('ras', 'ras')], max_length=1000),
        ),
    ]
