# Generated by Django 3.0.5 on 2020-07-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_auto_20200722_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='sdasdss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sadasd', models.CharField(max_length=1000)),
                ('sadas', models.CharField(max_length=1000)),
                ('sadasdas', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='sdasdssAccepted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=1000)),
                ('sadasd', models.CharField(max_length=1000)),
                ('sadas', models.CharField(max_length=1000)),
                ('sadasdas', models.DateField()),
            ],
        ),
    ]
