# Generated by Django 3.0.5 on 2020-12-11 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_test2_test2accepted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test1',
        ),
        migrations.DeleteModel(
            name='test1Accepted',
        ),
        migrations.DeleteModel(
            name='test2',
        ),
        migrations.DeleteModel(
            name='test2Accepted',
        ),
    ]
