# Generated by Django 3.0.5 on 2020-05-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_auto_20200505_0151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hello3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DVCD', models.CharField(max_length=100)),
                ('ENTERYOURAGE', models.TextField()),
                ('DATEOFBIRTH', models.DateTimeField()),
            ],
        ),
    ]
