# Generated by Django 3.0.7 on 2020-12-30 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_usernotifications_formname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test2',
        ),
        migrations.DeleteModel(
            name='test2Accepted',
        ),
    ]
