# Generated by Django 3.0.7 on 2020-12-02 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_test101_test101accepted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test101',
        ),
        migrations.DeleteModel(
            name='test101Accepted',
        ),
    ]
