# Generated by Django 3.0.5 on 2020-07-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_sdasdss_sdasdssaccepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='test4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_is_your_mother_name', models.CharField(max_length=1000)),
                ('mother', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='test4Accepted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=1000)),
                ('what_is_your_mother_name', models.CharField(max_length=1000)),
                ('mother', models.FileField(upload_to='')),
            ],
        ),
    ]
