# Generated by Django 3.0.5 on 2020-05-05 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_hello3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hello3',
        ),
    ]
