# Generated by Django 3.0.5 on 2020-05-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_delete_hello3'),
    ]

    operations = [
        migrations.CreateModel(
            name='sdsad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ASAS', models.TextField()),
                ('sdvfsvf', models.CharField(max_length=100)),
                ('age', models.DateField()),
            ],
        ),
    ]
