# Generated by Django 3.0.5 on 2020-07-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_test4_test4accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='test3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdasdas', models.CharField(max_length=1000)),
                ('sister_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='test3Accepted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=1000)),
                ('sdasdas', models.CharField(max_length=1000)),
                ('sister_name', models.CharField(max_length=1000)),
            ],
        ),
    ]
