# Generated by Django 3.0.5 on 2020-07-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_test3_test3accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='test1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_is_your_mother_name', models.CharField(max_length=1000)),
                ('mother', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='test1Accepted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=1000)),
                ('what_is_your_mother_name', models.CharField(max_length=1000)),
                ('mother', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='sdasdss',
        ),
        migrations.DeleteModel(
            name='sdasdssAccepted',
        ),
        migrations.DeleteModel(
            name='test3',
        ),
        migrations.DeleteModel(
            name='test3Accepted',
        ),
        migrations.DeleteModel(
            name='test4',
        ),
        migrations.DeleteModel(
            name='test4Accepted',
        ),
    ]
