# Generated by Django 3.0.7 on 2020-12-02 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_qw_qwaccepted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chahat1',
        ),
        migrations.DeleteModel(
            name='chahat1Accepted',
        ),
        migrations.DeleteModel(
            name='lk',
        ),
        migrations.DeleteModel(
            name='lkAccepted',
        ),
        migrations.DeleteModel(
            name='qw',
        ),
        migrations.DeleteModel(
            name='qwAccepted',
        ),
    ]
