# Generated by Django 3.0.5 on 2020-12-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_test43_test43accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotifications',
            name='linkToPage',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
