# Generated by Django 3.0.5 on 2020-05-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_auto_20200505_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hellodasdasdasdasd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enter_Your_Age', models.CharField(max_length=100)),
                ('Enter_Your_Name', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Hellosdasdfsd',
        ),
    ]
