# Generated by Django 3.0.5 on 2020-12-18 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0012_usernotifications_linktopage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test111',
        ),
        migrations.DeleteModel(
            name='test111Accepted',
        ),
        migrations.DeleteModel(
            name='test3',
        ),
        migrations.DeleteModel(
            name='test3Accepted',
        ),
        migrations.DeleteModel(
            name='test43',
        ),
        migrations.DeleteModel(
            name='test43Accepted',
        ),
    ]
