# Generated by Django 3.0.5 on 2020-05-05 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0012_auto_20200505_2129'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hellodasdasdasdasd',
            new_name='Hellofdf',
        ),
        migrations.RenameField(
            model_name='hellofdf',
            old_name='Enter_Your_Name',
            new_name='enter_your_date_of_place',
        ),
    ]
