# Generated by Django 3.0.7 on 2021-01-01 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0013_test2_test2accepted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test1',
        ),
        migrations.DeleteModel(
            name='test111',
        ),
        migrations.DeleteModel(
            name='test1Accepted',
        ),
        migrations.DeleteModel(
            name='test2',
        ),
        migrations.DeleteModel(
            name='test2Accepted',
        ),
    ]
