# Generated by Django 3.0.5 on 2020-05-05 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0013_auto_20200505_2331'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hellofdf',
        ),
    ]
