# Generated by Django 3.0.5 on 2020-08-01 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0014_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
