# Generated by Django 3.0.7 on 2020-12-02 19:10

import datetime
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0015_test102'),
    ]

    operations = [
        migrations.CreateModel(
            name='test102Accepted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responseTime', models.DateTimeField(auto_now_add=True)),
                ('comment', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('forwardTo', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(null=True), blank=True, default=list, size=None)),
                ('commentAccepted', models.CharField(blank=True, max_length=1000)),
                ('notification', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('userName', models.CharField(blank=True, max_length=1000)),
                ('what_is_your_name', models.CharField(max_length=1000)),
                ('a', models.CharField(max_length=1000)),
                ('sasasa', models.CharField(max_length=1000)),
                ('what_is_your_name_bfgf', models.CharField(max_length=1000)),
                ('naaam', models.CharField(max_length=1000)),
                ('dateee_dalo', models.DateField()),
                ('paragraphh_bhrooo', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='test102',
            name='a',
            field=models.CharField(default=datetime.datetime(2020, 12, 2, 19, 10, 21, 746571, tzinfo=utc), max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test102',
            name='dateee_dalo',
            field=models.DateField(default=datetime.datetime(2020, 12, 2, 19, 10, 24, 173775, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test102',
            name='naaam',
            field=models.CharField(default=datetime.datetime(2020, 12, 2, 19, 10, 26, 866068, tzinfo=utc), max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test102',
            name='paragraphh_bhrooo',
            field=models.TextField(default=datetime.datetime(2020, 12, 2, 19, 10, 29, 120064, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test102',
            name='sasasa',
            field=models.CharField(default=datetime.datetime(2020, 12, 2, 19, 10, 31, 566140, tzinfo=utc), max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test102',
            name='what_is_your_name',
            field=models.CharField(default=datetime.datetime(2020, 12, 2, 19, 10, 33, 231111, tzinfo=utc), max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test102',
            name='what_is_your_name_bfgf',
            field=models.CharField(default=datetime.datetime(2020, 12, 2, 19, 10, 35, 106653, tzinfo=utc), max_length=1000),
            preserve_default=False,
        ),
    ]
