# Generated by Django 3.0.7 on 2021-01-01 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0015_testing1_testing1accepted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testing1',
        ),
        migrations.DeleteModel(
            name='testing1Accepted',
        ),
    ]
