# Generated by Django 3.0.5 on 2020-12-19 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0016_test3_test3accepted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test1',
        ),
        migrations.DeleteModel(
            name='test1Accepted',
        ),
        migrations.DeleteModel(
            name='test2',
        ),
        migrations.DeleteModel(
            name='test2Accepted',
        ),
        migrations.DeleteModel(
            name='test3',
        ),
        migrations.DeleteModel(
            name='test3Accepted',
        ),
    ]
