# Generated by Django 3.0.5 on 2020-08-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0016_hello_helloaccepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='test3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enter_Your_Age', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='test3Accepted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=1000)),
                ('Enter_Your_Age', models.FileField(upload_to='')),
            ],
        ),
    ]
