# Generated by Django 3.0.5 on 2020-05-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0016_helloxsaxa'),
    ]

    operations = [
        migrations.CreateModel(
            name='aha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asacs', models.CharField(max_length=100)),
            ],
        ),
    ]
