# Generated by Django 3.0.1 on 2021-01-02 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0017_test1_test1accepted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test1',
        ),
        migrations.DeleteModel(
            name='test1Accepted',
        ),
    ]
