# Generated by Django 3.0.5 on 2020-08-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0017_test3_test3accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test3',
            name='Enter_Your_Age',
            field=models.ImageField(upload_to='post_images'),
        ),
    ]
