# Generated by Django 3.0.5 on 2020-05-07 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0017_aha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='aha',
        ),
    ]
