# Generated by Django 3.0.5 on 2020-05-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0020_hello4fcdavdsv'),
    ]

    operations = [
        migrations.CreateModel(
            name='FORM4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acacac', models.CharField(max_length=100)),
                ('Enter_Your_Age', models.CharField(max_length=100)),
            ],
        ),
    ]
