# Generated by Django 3.0.5 on 2020-12-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0020_purchase_form_purchase_formaccepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_form',
            name='userDept',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='purchase_formaccepted',
            name='userDept',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
