# Generated by Django 3.0.5 on 2020-08-02 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0020_test2_test2accepted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hello',
        ),
        migrations.DeleteModel(
            name='HelloAccepted',
        ),
        migrations.DeleteModel(
            name='test1',
        ),
        migrations.DeleteModel(
            name='test1Accepted',
        ),
        migrations.DeleteModel(
            name='test2',
        ),
        migrations.DeleteModel(
            name='test2Accepted',
        ),
        migrations.DeleteModel(
            name='test3',
        ),
        migrations.DeleteModel(
            name='test3Accepted',
        ),
    ]
