# Generated by Django 3.0.5 on 2020-11-04 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0020_test162_test162accepted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test1',
        ),
        migrations.DeleteModel(
            name='test102',
        ),
        migrations.DeleteModel(
            name='test102Accepted',
        ),
        migrations.DeleteModel(
            name='test112',
        ),
        migrations.DeleteModel(
            name='test112Accepted',
        ),
        migrations.DeleteModel(
            name='test122',
        ),
        migrations.DeleteModel(
            name='test122Accepted',
        ),
        migrations.DeleteModel(
            name='test132',
        ),
        migrations.DeleteModel(
            name='test132Accepted',
        ),
        migrations.DeleteModel(
            name='test142',
        ),
        migrations.DeleteModel(
            name='test142Accepted',
        ),
        migrations.DeleteModel(
            name='test152',
        ),
        migrations.DeleteModel(
            name='test152Accepted',
        ),
        migrations.DeleteModel(
            name='test162',
        ),
        migrations.DeleteModel(
            name='test162Accepted',
        ),
        migrations.DeleteModel(
            name='test1Accepted',
        ),
        migrations.DeleteModel(
            name='test32',
        ),
        migrations.DeleteModel(
            name='test32Accepted',
        ),
        migrations.DeleteModel(
            name='test42',
        ),
        migrations.DeleteModel(
            name='test42Accepted',
        ),
        migrations.DeleteModel(
            name='test52',
        ),
        migrations.DeleteModel(
            name='test52Accepted',
        ),
        migrations.DeleteModel(
            name='test62',
        ),
        migrations.DeleteModel(
            name='test62Accepted',
        ),
        migrations.DeleteModel(
            name='test72',
        ),
        migrations.DeleteModel(
            name='test72Accepted',
        ),
        migrations.DeleteModel(
            name='test82',
        ),
        migrations.DeleteModel(
            name='test82Accepted',
        ),
        migrations.DeleteModel(
            name='test92',
        ),
        migrations.DeleteModel(
            name='test92Accepted',
        ),
    ]
