# Generated by Django 3.0.5 on 2020-05-07 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0021_form4'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fcadfdv',
        ),
        migrations.DeleteModel(
            name='FORM4',
        ),
        migrations.DeleteModel(
            name='hello4fcdavdsv',
        ),
        migrations.DeleteModel(
            name='Helloxsaxa',
        ),
        migrations.DeleteModel(
            name='TAHDAS',
        ),
    ]
