# Generated by Django 3.0.1 on 2021-01-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0022_test4_test4accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=1000)),
                ('reciever', models.CharField(max_length=1000)),
                ('message', models.CharField(max_length=10000)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('acceptedResponseID', models.CharField(max_length=1000)),
            ],
        ),
    ]
