# Generated by Django 3.0.5 on 2020-12-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0022_test3_test3accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptname', models.CharField(max_length=1000)),
                ('committedamount', models.PositiveIntegerField()),
                ('spentamount', models.PositiveIntegerField()),
                ('recommendedamount', models.PositiveIntegerField()),
                ('pipelinedamount', models.PositiveIntegerField()),
                ('availableamount', models.PositiveIntegerField()),
                ('fundsleft', models.PositiveIntegerField()),
            ],
        ),
    ]
