# Generated by Django 3.0.1 on 2021-01-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0023_chatsystem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsystem',
            name='reciever',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
