# Generated by Django 3.0.5 on 2020-11-04 07:35

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0023_auto_20201104_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='test11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responseTime', models.DateTimeField(auto_now_add=True)),
                ('formStatus', models.BooleanField(default=False)),
                ('commentRejected', models.CharField(blank=True, max_length=1000)),
                ('userName', models.CharField(blank=True, max_length=1000)),
                ('userMail', models.EmailField(blank=True, max_length=1000)),
                ('Endfd', models.CharField(max_length=1000)),
                ('Enter_gasdasd', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='test11Accepted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responseTime', models.DateTimeField(auto_now_add=True)),
                ('comment', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('forwardTo', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(null=True), blank=True, default=list, size=None)),
                ('commentAccepted', models.CharField(blank=True, max_length=1000)),
                ('notification', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('userName', models.CharField(blank=True, max_length=1000)),
                ('Endfd', models.CharField(max_length=1000)),
                ('Enter_gasdasd', models.CharField(max_length=1000)),
            ],
        ),
    ]
