# Generated by Django 3.0.5 on 2020-12-27 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0023_departmentdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departmentdetail',
            old_name='fundsleft',
            new_name='expenditureamount',
        ),
        migrations.RemoveField(
            model_name='departmentdetail',
            name='spentamount',
        ),
    ]
