# Generated by Django 3.0.5 on 2020-05-07 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0024_hello'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hello',
        ),
        migrations.DeleteModel(
            name='Hellosdsa',
        ),
    ]
