# Generated by Django 3.0.5 on 2020-11-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0024_test11_test11accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senderEmail', models.EmailField(max_length=1000)),
                ('recieverEmail', models.EmailField(max_length=1000)),
                ('content', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='test11',
        ),
        migrations.DeleteModel(
            name='test11Accepted',
        ),
    ]
