# Generated by Django 3.0.5 on 2020-05-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0026_safepopm'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAFePOPMnfhnhnhdg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enter_Your_Age', models.CharField(max_length=100)),
                ('acacac', models.TextField()),
                ('enter_your_date_of_birth', models.DateField()),
            ],
        ),
    ]
