# Generated by Django 3.0.5 on 2020-11-06 07:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0027_test2_test2accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailindex',
            name='sentDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
