# Generated by Django 3.0.5 on 2020-05-07 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0027_safepopmnfhnhnhdg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SAFePOPM',
        ),
        migrations.DeleteModel(
            name='SAFePOPMnfhnhnhdg',
        ),
    ]
