# Generated by Django 3.0.5 on 2020-06-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0028_auto_20200507_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hellodsa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enter_Your_Age', models.CharField(max_length=100)),
            ],
        ),
    ]
