# Generated by Django 3.0.5 on 2020-11-13 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0029_test5_test5accepted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test1',
        ),
        migrations.DeleteModel(
            name='test1Accepted',
        ),
        migrations.DeleteModel(
            name='test2',
        ),
        migrations.DeleteModel(
            name='test2Accepted',
        ),
        migrations.DeleteModel(
            name='test5',
        ),
        migrations.DeleteModel(
            name='test5Accepted',
        ),
    ]
