# Generated by Django 3.0.5 on 2020-06-12 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0029_hellodsa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hellodsa',
        ),
    ]
