# Generated by Django 3.0.5 on 2020-11-13 12:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0030_auto_20201113_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedusers',
            name='linkedForms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), blank=True, default=list, size=None),
        ),
    ]
