# Generated by Django 3.0.5 on 2020-06-12 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0030_delete_hellodsa'),
    ]

    operations = [
        migrations.AddField(
            model_name='createforms',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='createform', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formname',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formName', to=settings.AUTH_USER_MODEL),
        ),
    ]
