# Generated by Django 3.0.5 on 2020-06-12 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0031_auto_20200612_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createforms',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='createForm', to=settings.AUTH_USER_MODEL),
        ),
    ]
