# Generated by Django 3.0.5 on 2020-11-14 01:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0032_test9_test9accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedusers',
            name='linkedForms',
        ),
        migrations.AddField(
            model_name='formname',
            name='linkedForms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), blank=True, default=list, size=None),
        ),
    ]
