# Generated by Django 3.0.5 on 2020-06-12 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0033_hello'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hello',
            new_name='SAFePOPM',
        ),
    ]
