# Generated by Django 3.0.5 on 2020-06-12 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0034_auto_20200612_2109'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SAFePOPM',
        ),
    ]
