# Generated by Django 3.0.5 on 2020-11-14 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0036_test23_test23accepted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test133',
        ),
        migrations.DeleteModel(
            name='test133Accepted',
        ),
        migrations.DeleteModel(
            name='test22',
        ),
        migrations.DeleteModel(
            name='test22Accepted',
        ),
        migrations.DeleteModel(
            name='test23',
        ),
        migrations.DeleteModel(
            name='test23Accepted',
        ),
        migrations.DeleteModel(
            name='test9',
        ),
        migrations.DeleteModel(
            name='test9Accepted',
        ),
    ]
