# Generated by Django 3.0.5 on 2020-06-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0036_helloadsasd'),
    ]

    operations = [
        migrations.CreateModel(
            name='csacac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acacac', models.CharField(max_length=100)),
                ('Enter_Your_Age', models.CharField(max_length=100)),
                ('acacacadsa', models.CharField(max_length=100)),
                ('cdxvzx', models.CharField(max_length=100)),
            ],
        ),
    ]
