# Generated by Django 3.0.5 on 2020-06-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0038_safepopm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Helloadssada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acacacadsa', models.CharField(max_length=100)),
                ('cdxvzx', models.CharField(max_length=100)),
                ('acacac', models.CharField(max_length=100)),
                ('Enter_Your_Age', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='csacac',
        ),
        migrations.DeleteModel(
            name='Helloadsasd',
        ),
        migrations.DeleteModel(
            name='SAFePOPM',
        ),
    ]
