# Generated by Django 3.0.5 on 2020-06-13 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0039_auto_20200613_1047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Helloadssada',
        ),
    ]
