# Generated by Django 3.0.5 on 2020-06-13 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0041_hellodasd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hellodasd',
        ),
    ]
