# Generated by Django 3.0.5 on 2020-06-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0042_delete_hellodasd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hello',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enter_Your_Age', models.TextField()),
            ],
        ),
    ]
