# Generated by Django 3.0.5 on 2020-06-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0043_hello'),
    ]

    operations = [
        migrations.CreateModel(
            name='cxzCzx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enter_Your_Age', models.TextField()),
                ('aasd', models.TextField()),
                ('cxzc', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Hello',
        ),
    ]
