# Generated by Django 3.0.5 on 2020-06-17 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0045_asasa_chahahattt_jatin_test1'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAFePOPM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enter_Your_Age', models.CharField(max_length=100)),
                ('cxzc', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='asasa',
        ),
        migrations.DeleteModel(
            name='chahahattt',
        ),
        migrations.DeleteModel(
            name='cxzCzx',
        ),
        migrations.DeleteModel(
            name='jatin',
        ),
        migrations.DeleteModel(
            name='test1',
        ),
    ]
