# Generated by Django 3.0.5 on 2020-06-17 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0046_auto_20200617_0715'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SAFePOPM',
            new_name='Hello',
        ),
    ]
