# Generated by Django 2.0.2 on 2020-06-17 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0047_auto_20200617_0727'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hello',
        ),
    ]
