# Generated by Django 2.0.2 on 2020-06-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0052_new2'),
    ]

    operations = [
        migrations.CreateModel(
            name='testdynamic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fdafad', models.CharField(max_length=100)),
                ('dsds', models.TextField()),
                ('dsd', models.CharField(max_length=100)),
                ('what_is_your_mother_name', models.TextField()),
                ('haja', models.CharField(max_length=100)),
            ],
        ),
    ]
