# Generated by Django 2.0.2 on 2020-06-19 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0056_auto_20200619_1706'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dsds',
        ),
        migrations.DeleteModel(
            name='jatin',
        ),
        migrations.DeleteModel(
            name='new',
        ),
        migrations.DeleteModel(
            name='new2',
        ),
        migrations.DeleteModel(
            name='newform',
        ),
        migrations.DeleteModel(
            name='test3',
        ),
        migrations.DeleteModel(
            name='testdynamic',
        ),
    ]
