# Generated by Django 2.0.2 on 2020-06-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0057_auto_20200619_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='test1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_is_your_mother_name', models.CharField(max_length=100)),
                ('asdasd', models.CharField(max_length=100)),
                ('adadasd', models.CharField(max_length=100)),
            ],
        ),
    ]
