# Generated by Django 2.0.2 on 2020-06-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0058_test1'),
    ]

    operations = [
        migrations.CreateModel(
            name='test3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsd', models.CharField(max_length=100)),
                ('haja', models.CharField(max_length=100)),
            ],
        ),
    ]
