# Generated by Django 2.0.2 on 2020-06-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0059_test3'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_final',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_is_your_mother_name', models.CharField(max_length=100)),
                ('what_is_your_sdaasdas', models.CharField(max_length=100)),
                ('hjauiauia', models.TextField()),
            ],
        ),
    ]
