# Generated by Django 3.0.5 on 2020-06-20 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0060_test_final'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='test_final',
            new_name='SAFePOPM',
        ),
        migrations.DeleteModel(
            name='test1',
        ),
        migrations.DeleteModel(
            name='test3',
        ),
    ]
