# Generated by Django 3.0.5 on 2020-06-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0061_auto_20200621_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hello1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_is_your_mother_name', models.CharField(max_length=100)),
                ('what_is_your_sdaasdas', models.CharField(max_length=100)),
                ('hjauiauia', models.TextField()),
                ('cxzc', models.CharField(max_length=100)),
            ],
        ),
    ]
