# Generated by Django 3.0.5 on 2020-06-21 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0062_hello1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hello1',
        ),
        migrations.DeleteModel(
            name='SAFePOPM',
        ),
    ]
