# Generated by Django 3.0.5 on 2020-06-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0063_auto_20200621_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hello',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enter_Your_Age', models.CharField(max_length=100)),
                ('acacac', models.CharField(max_length=100)),
                ('enter_your_date_of_birth', models.CharField(max_length=100)),
            ],
        ),
    ]
