# Generated by Django 3.0.5 on 2020-06-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0066_asdzcx'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAFePOPMzxczxc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zcxxzc', models.CharField(max_length=100)),
                ('acacac', models.CharField(max_length=100)),
            ],
        ),
    ]
