# Generated by Django 3.0.5 on 2020-06-21 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0068_adcxzzxczxc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='adcxzzxczxc',
        ),
        migrations.DeleteModel(
            name='asdzcx',
        ),
        migrations.DeleteModel(
            name='Hello',
        ),
        migrations.DeleteModel(
            name='Hello1',
        ),
        migrations.DeleteModel(
            name='SAFePOPMzxczxc',
        ),
    ]
