# Generated by Django 3.0.5 on 2020-06-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0069_auto_20200621_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hello1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enter_Your_Age', models.CharField(max_length=100)),
                ('acacac', models.CharField(max_length=100)),
            ],
        ),
    ]
