# Generated by Django 3.0.5 on 2020-06-21 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0071_auto_20200621_1641'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SAFdsePOPM',
        ),
    ]
