# Generated by Django 2.0.2 on 2020-06-23 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0078_test10'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test10',
        ),
        migrations.DeleteModel(
            name='test3',
        ),
        migrations.DeleteModel(
            name='test4',
        ),
        migrations.DeleteModel(
            name='test5',
        ),
    ]
