# Generated by Django 2.0.2 on 2020-06-24 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0084_test4'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test1',
        ),
        migrations.DeleteModel(
            name='test2',
        ),
        migrations.DeleteModel(
            name='test3',
        ),
        migrations.DeleteModel(
            name='test4',
        ),
        migrations.DeleteModel(
            name='zvczxxcv',
        ),
    ]
