# Generated by Django 3.0.5 on 2020-06-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0086_test1'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralForms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formName', models.CharField(max_length=100, unique=True)),
                ('question', models.CharField(max_length=100)),
                ('inputType', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='test1',
        ),
    ]
