# Generated by Django 3.0.5 on 2020-06-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0087_auto_20200625_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalforms',
            name='formName',
            field=models.CharField(max_length=100),
        ),
    ]
