# Generated by Django 3.0.5 on 2020-06-25 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0088_auto_20200626_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createforms',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='formname',
            name='owner',
        ),
        migrations.DeleteModel(
            name='GeneralForms',
        ),
        migrations.DeleteModel(
            name='CreateForms',
        ),
        migrations.DeleteModel(
            name='FormName',
        ),
    ]
