# Generated by Django 3.0.5 on 2020-06-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0090_createforms_formname_generalforms'),
    ]

    operations = [
        migrations.CreateModel(
            name='asdcvb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enter_Your_Agezxczxc', models.CharField(max_length=100)),
                ('vczxv', models.CharField(max_length=100)),
                ('mbj', models.CharField(max_length=100)),
                ('enter_your_date_of_birth', models.CharField(max_length=100)),
                ('cxzc', models.CharField(max_length=100)),
                ('Enter_Your_Age', models.CharField(max_length=100)),
                ('Enter_Your_Agesadzxczxc', models.CharField(max_length=100)),
                ('csdcd', models.CharField(max_length=100)),
                ('acacac', models.CharField(max_length=100)),
            ],
        ),
    ]
