# Generated by Django 3.0.5 on 2020-06-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0091_asdcvb'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAFePOPM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acacac', models.CharField(max_length=100)),
                ('Enter_Your_Age', models.CharField(max_length=100)),
            ],
        ),
    ]
