# Generated by Django 2.0.2 on 2020-06-26 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0093_helloasdacxz1425'),
    ]

    operations = [
        migrations.DeleteModel(
            name='asdcvb',
        ),
        migrations.RemoveField(
            model_name='createforms',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='formname',
            name='owner',
        ),
        migrations.DeleteModel(
            name='GeneralForms',
        ),
        migrations.DeleteModel(
            name='Helloasdacxz1425',
        ),
        migrations.DeleteModel(
            name='SAFePOPM',
        ),
        migrations.DeleteModel(
            name='CreateForms',
        ),
        migrations.DeleteModel(
            name='FormName',
        ),
    ]
