# Generated by Django 3.0.5 on 2020-06-26 12:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0099_test4'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test2',
        ),
        migrations.DeleteModel(
            name='test3',
        ),
        migrations.DeleteModel(
            name='test4',
        ),
        migrations.AddField(
            model_name='test1',
            name='father',
            field=models.CharField(default=datetime.datetime(2020, 6, 26, 12, 8, 3, 703935, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
