# Generated by Django 3.0.5 on 2020-06-26 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0100_auto_20200626_1738'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test1',
        ),
    ]
