# Generated by Django 3.0.5 on 2020-06-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0102_test1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='test2112',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sister_name', models.CharField(max_length=100)),
                ('job_name', models.CharField(max_length=100)),
            ],
        ),
    ]
