# Generated by Django 3.0.5 on 2020-06-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0106_test2'),
    ]

    operations = [
        migrations.CreateModel(
            name='test103',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_is_your_mother_name', models.CharField(max_length=100)),
                ('dsd', models.CharField(max_length=100)),
                ('dsa', models.CharField(max_length=100)),
                ('mother', models.CharField(max_length=100)),
                ('jatin', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='test1',
        ),
        migrations.DeleteModel(
            name='test1221',
        ),
        migrations.DeleteModel(
            name='test1223',
        ),
        migrations.DeleteModel(
            name='test2',
        ),
        migrations.DeleteModel(
            name='test2112',
        ),
    ]
