# Generated by Django 3.0.5 on 2020-06-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0110_test106'),
    ]

    operations = [
        migrations.CreateModel(
            name='test1001',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_is_your_mother_name', models.CharField(max_length=100)),
                ('dsd', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='test103',
        ),
        migrations.DeleteModel(
            name='test104',
        ),
        migrations.DeleteModel(
            name='test105',
        ),
        migrations.DeleteModel(
            name='test106',
        ),
    ]
