# Generated by Django 3.0.5 on 2020-06-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0111_auto_20200627_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='test1002',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sister_name', models.CharField(max_length=100)),
            ],
        ),
    ]
