# Generated by Django 3.0.5 on 2020-06-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0112_test1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='test104',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsd', models.CharField(max_length=100)),
                ('dasdsa', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='test1001',
        ),
        migrations.DeleteModel(
            name='test1002',
        ),
    ]
