# Generated by Django 3.0.7 on 2020-06-27 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0114_test1022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test1022',
        ),
        migrations.DeleteModel(
            name='test104',
        ),
    ]
