# Generated by Django 3.0.5 on 2020-06-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0116_hello'),
    ]

    operations = [
        migrations.CreateModel(
            name='test103',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_is_your_mother_name', models.CharField(max_length=1000)),
                ('father', models.CharField(max_length=1000)),
                ('qualification', models.CharField(max_length=1000)),
            ],
        ),
    ]
