# Generated by Django 3.0.5 on 2020-06-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0120_test107'),
    ]

    operations = [
        migrations.CreateModel(
            name='test108',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_is_your_mother_name', models.CharField(max_length=1000)),
                ('mother', models.CharField(max_length=1000)),
                ('father_name', models.CharField(max_length=1000)),
                ('fdafad', models.CharField(max_length=1000)),
                ('raghav', models.TextField()),
            ],
        ),
    ]
