# Generated by Django 3.0.5 on 2020-06-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0121_test108'),
    ]

    operations = [
        migrations.CreateModel(
            name='test109',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mother', models.CharField(max_length=1000)),
                ('father_name', models.CharField(max_length=1000)),
                ('fdafad', models.CharField(max_length=1000)),
                ('raghav', models.TextField()),
                ('what_is_yo', models.CharField(max_length=1000)),
            ],
        ),
    ]
