# Generated by Django 3.0.5 on 2020-06-30 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0122_test109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formname',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='formname',
            name='owner',
        ),
    ]
