# Generated by Django 3.0.5 on 2020-06-30 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0123_auto_20200630_2133'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hello',
        ),
        migrations.DeleteModel(
            name='test103',
        ),
        migrations.DeleteModel(
            name='test105',
        ),
        migrations.DeleteModel(
            name='test106',
        ),
        migrations.DeleteModel(
            name='test107',
        ),
        migrations.DeleteModel(
            name='test108',
        ),
        migrations.DeleteModel(
            name='test109',
        ),
    ]
