# Generated by Django 3.0.5 on 2020-06-30 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0128_test105'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test103',
        ),
        migrations.DeleteModel(
            name='test104',
        ),
        migrations.DeleteModel(
            name='test105',
        ),
    ]
