# Generated by Django 3.0.5 on 2020-07-01 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0136_test3'),
    ]

    operations = [
        migrations.CreateModel(
            name='test101',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sister_name', models.CharField(max_length=1000)),
                ('mother', models.CharField(max_length=1000)),
            ],
        ),
    ]
