# Generated by Django 3.0.5 on 2020-07-01 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0137_test101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test101',
        ),
        migrations.DeleteModel(
            name='test104',
        ),
        migrations.DeleteModel(
            name='test2',
        ),
        migrations.DeleteModel(
            name='test3',
        ),
    ]
