# Generated by Django 3.0.5 on 2020-07-01 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0140_test102'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test101',
        ),
        migrations.DeleteModel(
            name='test102',
        ),
    ]
