# Generated by Django 3.0.5 on 2020-07-01 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0141_auto_20200701_0635'),
    ]

    operations = [
        migrations.CreateModel(
            name='test1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsd', models.CharField(max_length=1000)),
                ('sister_name', models.CharField(max_length=1000)),
            ],
        ),
    ]
