# Generated by Django 3.0.5 on 2020-07-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0142_test1'),
    ]

    operations = [
        migrations.CreateModel(
            name='test101',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sister', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='test1',
        ),
    ]
