# Generated by Django 3.0.5 on 2020-07-02 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0143_auto_20200702_1425'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test101',
        ),
    ]
