# Generated by Django 3.0.5 on 2020-07-02 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0147_test301'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test101',
        ),
        migrations.DeleteModel(
            name='test102',
        ),
        migrations.DeleteModel(
            name='test301',
        ),
    ]
