# Generated by Django 3.0.5 on 2020-07-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0148_auto_20200702_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='test101',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ada', models.CharField(max_length=1000)),
                ('daadda', models.CharField(max_length=1000)),
                ('adada', models.CharField(max_length=1000)),
            ],
        ),
    ]
