# Generated by Django 3.0.5 on 2020-07-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0151_userperm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userperm',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
