# Generated by Django 3.0.5 on 2020-07-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0152_auto_20200702_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAFePOPM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acacac', models.CharField(max_length=1000)),
            ],
        ),
    ]
