# Generated by Django 3.0.5 on 2020-07-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0154_helloas'),
    ]

    operations = [
        migrations.CreateModel(
            name='sad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enter_Your_Age', models.CharField(max_length=1000)),
            ],
        ),
    ]
