# Generated by Django 3.0.5 on 2020-07-03 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0156_helloasdxcz'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Helloas',
        ),
        migrations.DeleteModel(
            name='Helloasdxcz',
        ),
        migrations.DeleteModel(
            name='sad',
        ),
        migrations.DeleteModel(
            name='SAFePOPM',
        ),
        migrations.DeleteModel(
            name='test101',
        ),
        migrations.DeleteModel(
            name='test102',
        ),
    ]
