# Generated by Django 3.0.5 on 2020-07-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0158_test1'),
    ]

    operations = [
        migrations.CreateModel(
            name='test2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acacac', models.TextField()),
                ('Enter_Your_Age', models.CharField(max_length=1000)),
            ],
        ),
    ]
