# Generated by Django 3.0.5 on 2020-07-03 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0159_test2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test1',
        ),
        migrations.DeleteModel(
            name='test2',
        ),
    ]
