# Generated by Django 3.0.5 on 2020-07-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0160_auto_20200703_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='test1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enter_Your_Age', models.CharField(max_length=1000)),
                ('acacac', models.CharField(max_length=1000)),
                ('csdcd', models.CharField(max_length=1000)),
            ],
        ),
    ]
