# Generated by Django 3.0.5 on 2020-07-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0161_test1'),
    ]

    operations = [
        migrations.CreateModel(
            name='test2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enter_Your_Ageasdasd', models.CharField(max_length=1000)),
                ('asdsfdscsa', models.CharField(max_length=1000)),
            ],
        ),
    ]
