# Generated by Django 3.0.5 on 2020-07-03 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0163_test3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test1',
        ),
        migrations.DeleteModel(
            name='test2',
        ),
        migrations.DeleteModel(
            name='test3',
        ),
    ]
