# Generated by Django 3.0.5 on 2020-07-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0166_auto_20200704_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='test102',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adaa', models.CharField(max_length=1000)),
                ('adadadaf', models.CharField(max_length=1000)),
            ],
        ),
    ]
