# Generated by Django 3.0.5 on 2020-07-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0167_test102'),
    ]

    operations = [
        migrations.CreateModel(
            name='test1011',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amother', models.CharField(max_length=1000)),
                ('aftaher', models.CharField(max_length=1000)),
                ('adadadafda', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='test101',
        ),
        migrations.DeleteModel(
            name='test102',
        ),
    ]
