# Generated by Django 3.0.5 on 2020-07-03 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0168_auto_20200704_0043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test1011',
        ),
    ]
