# Generated by Django 3.0.5 on 2020-07-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0169_delete_test1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='adadadda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adadada', models.CharField(max_length=1000)),
                ('adadafsrgfsef', models.CharField(max_length=1000)),
                ('adagsgs', models.CharField(max_length=1000)),
            ],
        ),
    ]
