# Generated by Django 3.0.5 on 2020-07-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0170_adadadda'),
    ]

    operations = [
        migrations.CreateModel(
            name='dadad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afwefew', models.CharField(max_length=1000)),
                ('sfsfdsfs', models.CharField(max_length=1000)),
                ('zfzfefse', models.CharField(max_length=1000)),
            ],
        ),
    ]
