# Generated by Django 3.0.5 on 2020-07-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0172_test104'),
    ]

    operations = [
        migrations.CreateModel(
            name='test107',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_is_your_mother_name', models.CharField(max_length=1000)),
                ('dsd', models.CharField(max_length=1000)),
                ('mother', models.CharField(max_length=1000)),
                ('sister_name', models.CharField(max_length=1000)),
                ('father_name', models.CharField(max_length=1000)),
                ('fdafad', models.CharField(max_length=1000)),
                ('fhjdshfjdsa', models.CharField(max_length=1000)),
                ('sdasdasd', models.CharField(max_length=1000)),
                ('dasdasdas', models.CharField(max_length=1000)),
                ('dsadasdas', models.CharField(max_length=1000)),
                ('sdasdas', models.CharField(max_length=1000)),
            ],
        ),
    ]
