# Generated by Django 3.0.5 on 2020-07-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0173_test107'),
    ]

    operations = [
        migrations.CreateModel(
            name='test101',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_is_your_mother_name', models.CharField(max_length=1000)),
                ('mother', models.CharField(max_length=1000)),
                ('sister_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='adadadda',
        ),
        migrations.DeleteModel(
            name='dadad',
        ),
        migrations.DeleteModel(
            name='test104',
        ),
        migrations.DeleteModel(
            name='test107',
        ),
    ]
