# Generated by Django 3.0.5 on 2020-07-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0174_auto_20200706_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='test3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_is_your_name', models.CharField(max_length=1000)),
                ('what_is_your_father_name', models.TextField()),
                ('fdafad', models.TextField()),
                ('jhgjghjhg', models.TextField()),
                ('ghjghjghj', models.TextField()),
            ],
        ),
    ]
