# Generated by Django 3.0.5 on 2020-07-08 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0175_test3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test101',
        ),
        migrations.DeleteModel(
            name='test3',
        ),
    ]
