# Generated by Django 3.0.5 on 2020-07-08 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0177_test102'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test102',
        ),
    ]
