# Generated by Django 3.0.5 on 2020-07-08 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0179_test1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test1',
        ),
    ]
