# Generated by Django 3.0.5 on 2020-07-08 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0183_auto_20200708_2049'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test1',
        ),
    ]
