# Generated by Django 3.0.7 on 2020-07-08 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0187_test1_test1accepted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test1',
        ),
        migrations.DeleteModel(
            name='test1Accepted',
        ),
    ]
