# Generated by Django 3.0.5 on 2020-07-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0187_test1_test1accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='test101',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enter_Your_Age', models.TextField()),
                ('acacac', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='test101Accepted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enter_Your_Age', models.TextField()),
                ('acacac', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='test1',
        ),
        migrations.DeleteModel(
            name='test1Accepted',
        ),
    ]
