# Generated by Django 3.0.5 on 2020-07-08 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0188_auto_20200709_0300'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test101',
        ),
        migrations.DeleteModel(
            name='test101Accepted',
        ),
    ]
