# Generated by Django 3.0.5 on 2020-07-08 21:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0192_test1_test1accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test1',
            name='cxzc',
        ),
        migrations.RemoveField(
            model_name='test1',
            name='enter_your_date_of_birth',
        ),
        migrations.RemoveField(
            model_name='test1accepted',
            name='cxzc',
        ),
        migrations.RemoveField(
            model_name='test1accepted',
            name='enter_your_date_of_birth',
        ),
        migrations.AddField(
            model_name='test1',
            name='acacac',
            field=models.CharField(default=datetime.datetime(2020, 7, 8, 21, 51, 52, 430198, tzinfo=utc), max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test1',
            name='csdcd',
            field=models.CharField(default=datetime.datetime(2020, 7, 8, 21, 51, 58, 931465, tzinfo=utc), max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test1accepted',
            name='acacac',
            field=models.CharField(default=datetime.datetime(2020, 7, 8, 21, 52, 6, 262315, tzinfo=utc), max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test1accepted',
            name='csdcd',
            field=models.CharField(default=datetime.datetime(2020, 7, 8, 21, 52, 14, 49290, tzinfo=utc), max_length=1000),
            preserve_default=False,
        ),
    ]
