# Generated by Django 3.0.5 on 2020-07-08 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0193_auto_20200709_0322'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test1',
        ),
        migrations.DeleteModel(
            name='test1Accepted',
        ),
    ]
