# Generated by Django 3.0.7 on 2020-07-08 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0195_test1_test1accepted'),
        ('forms', '0190_test2_test2accepted'),
    ]

    operations = [
    ]
