# Generated by Django 3.0.7 on 2020-07-08 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0196_merge_20200709_0404'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test1',
        ),
        migrations.DeleteModel(
            name='test1Accepted',
        ),
        migrations.DeleteModel(
            name='test2',
        ),
        migrations.DeleteModel(
            name='test2Accepted',
        ),
    ]
