# Generated by Django 3.0.7 on 2020-07-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0197_auto_20200709_0404'),
    ]

    operations = [
        migrations.CreateModel(
            name='test1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_is_your_occupation', models.CharField(max_length=1000)),
                ('what_is_your_name', models.CharField(max_length=1000)),
                ('father_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='test1Accepted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_is_your_occupation', models.CharField(max_length=1000)),
                ('what_is_your_name', models.CharField(max_length=1000)),
                ('father_name', models.CharField(max_length=1000)),
            ],
        ),
    ]
