# Generated by Django 3.0.5 on 2020-07-09 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0201_test4_test4accepted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test1',
        ),
        migrations.DeleteModel(
            name='test1Accepted',
        ),
        migrations.DeleteModel(
            name='test2',
        ),
        migrations.DeleteModel(
            name='test2Accepted',
        ),
        migrations.DeleteModel(
            name='test3',
        ),
        migrations.DeleteModel(
            name='test3Accepted',
        ),
        migrations.DeleteModel(
            name='test4',
        ),
        migrations.DeleteModel(
            name='test4Accepted',
        ),
    ]
