# Generated by Django 3.0.5 on 2020-07-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0203_test2_test2accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hello',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enter_Your_Age', models.CharField(max_length=1000)),
                ('cxzc', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='HelloAccepted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=1000)),
                ('Enter_Your_Age', models.CharField(max_length=1000)),
                ('cxzc', models.CharField(max_length=1000)),
            ],
        ),
    ]
