# Generated by Django 3.0.5 on 2020-07-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_good',
            new_name='can_generate_form',
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_generate_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_make_noting',
            field=models.BooleanField(default=False),
        ),
    ]
